name: Build SukiSU
on:
  push:
    branches:
      - "sukisu_susfs"
      - "sukisu"
      - "sukisu-A045FXXSCEYJ2"
      - "resukisu-A045FXXSCEYJ2"
  workflow_dispatch:

jobs:
  build:
    name: Build ReSukiSU
    runs-on: ubuntu-22.04
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"
    steps:
      - uses: actions/checkout@v4
      - name: Prepare Configuration
        run: |
          CONFIG_ENV=$(grep -w "CONFIG_ENV" resukiconfig.env | head -n 1 | cut -d "=" -f 2)
          CONFIG_LIST=(
              KERNEL_SOURCE
              KERNEL_SOURCE_BRANCH
              KERNEL_CONFIG
              KERNEL_IMAGE_NAME
              ARCH
              ADD_LOCALVERSION_TO_FILENAME
              EXTRA_CMDS
              USE_CUSTOM_CLANG
              CUSTOM_CLANG_SOURCE
              CUSTOM_CLANG_BRANCH
              CUSTOM_CMDS
              CLANG_BRANCH
              CLANG_VERSION
              ENABLE_GCC_ARM64
              ENABLE_GCC_ARM32
              USE_CUSTOM_GCC_64
              CUSTOM_GCC_64_SOURCE
              CUSTOM_GCC_64_BRANCH
              CUSTOM_GCC_64_BIN
              USE_CUSTOM_GCC_32
              CUSTOM_GCC_32_SOURCE
              CUSTOM_GCC_32_BRANCH
              CUSTOM_GCC_32_BIN
              DISABLE-LTO
              DISABLE_CC_WERROR
              USE_CUSTOM_ANYKERNEL3
              CUSTOM_ANYKERNEL3_SOURCE
              CUSTOM_ANYKERNEL3_BRANCH
              ENABLE_CCACHE
              NEED_DTBO
              BUILD_BOOT_IMG
              SOURCE_BOOT_IMAGE
              REMOVE_UNUSED_PACKAGES
              ENABLE_RESUKISU
              RESUKISU_TAG
              ENABLE_KPM
              SUSFS_ENABLE
              HIDE_STUFF
          )
          
          for CONFIG in "${CONFIG_LIST[@]}"; do
              if [[ "$CONFIG" == "EXTRA_CMDS" || "$CONFIG" == "CUSTOM_CMDS" ]]; then
                  echo "$CONFIG=$(grep -w "$CONFIG" "$CONFIG_ENV" | head -n 1 | cut -d ":" -f 2)" >> $GITHUB_ENV
              else
                  echo "$CONFIG=$(grep -w "$CONFIG" "$CONFIG_ENV" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
              fi
          done

      - name: Remove unused packages
        if: env.REMOVE_UNUSED_PACKAGES == 'true'
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: false
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: false

      - name: Set swap to 10G
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10

      - name: Setup build kernel environment
        run: |
          echo "BUILD_TIME=$(TZ=Asia/Shanghai date "+%Y%m%d%H%M")" >> $GITHUB_ENV
          echo "DEVICE=$(echo ${{ env.KERNEL_CONFIG }} | sed 's!vendor/!!;s/_defconfig//;s/_user//;s/-perf//')" >> $GITHUB_ENV
          sudo apt-get update
          sudo apt-get install git ccache automake flex lzop bison gperf build-essential zip curl zlib1g-dev g++-multilib libxml2-utils bzip2 libbz2-dev libbz2-1.0 libghc-bzlib-dev squashfs-tools pngcrush schedtool dpkg-dev liblz4-tool make optipng maven libssl-dev pwgen libswitch-perl policycoreutils minicom libxml-sax-base-perl libxml-simple-perl bc libc6-dev-i386 lib32ncurses5-dev libx11-dev lib32z-dev libgl1-mesa-dev xsltproc unzip device-tree-compiler python2 python3 libyaml-dev
          mkdir -p $GITHUB_WORKSPACE/kernel_workspace
          
          if [[ ${{ env.HIDE_STUFF }} == true ]]; then
              sudo apt-get install -y coccinelle
          fi

      - name: Download Clang-aosp
        if: env.USE_CUSTOM_CLANG != 'true'
        run: |
          cd $GITHUB_WORKSPACE/kernel_workspace
          mkdir clang-aosp
          wget https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/${{ env.CLANG_BRANCH }}/clang-${{ env.CLANG_VERSION }}.tar.gz
          tar -C clang-aosp/ -zxvf clang-${{ env.CLANG_VERSION }}.tar.gz

      - name: Download Custom-Clang
        if: env.USE_CUSTOM_CLANG == 'true'
        run: |
          cd $GITHUB_WORKSPACE/kernel_workspace
          if [[ ${{ env.CUSTOM_CLANG_SOURCE }} =~ git ]]; then
              if [[ ${{ env.CUSTOM_CLANG_SOURCE }} == *'.tar.gz' ]]; then
                  wget -O clang.tar.gz ${{ env.CUSTOM_CLANG_SOURCE }}
                  mkdir clang-aosp
                  tar -C clang-aosp/ -zxvf clang.tar.gz
              else
                  git clone ${{ env.CUSTOM_CLANG_SOURCE }} -b ${{ env.CUSTOM_CLANG_BRANCH }} clang-aosp --depth=1
              fi
          else
              wget -O clang.zip ${{ env.CUSTOM_CLANG_SOURCE }}
              mkdir clang-aosp
              unzip clang.zip -d clang-aosp/
          fi

      - name: Download Gcc-aosp
        if: env.USE_CUSTOM_GCC_64 != 'true' || env.USE_CUSTOM_GCC_32 != 'true'
        run: |
          cd $GITHUB_WORKSPACE/kernel_workspace
          if [ ${{ env.ENABLE_GCC_ARM64 }} = true ]; then
              mkdir gcc-64
              wget -O gcc-aarch64.tar.gz https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/+archive/refs/tags/android-12.1.0_r27.tar.gz
              tar -C gcc-64/ -zxvf gcc-aarch64.tar.gz
              echo "GCC_64=CROSS_COMPILE=$GITHUB_WORKSPACE/kernel_workspace/gcc-64/bin/aarch64-linux-android-" >> $GITHUB_ENV
          fi
          
          if [ ${{ env.ENABLE_GCC_ARM32 }} = true ]; then
              mkdir gcc-32
              wget -O gcc-arm.tar.gz https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/+archive/refs/tags/android-12.1.0_r27.tar.gz
              tar -C gcc-32/ -zxvf gcc-arm.tar.gz
              echo "GCC_32=CROSS_COMPILE_ARM32=$GITHUB_WORKSPACE/kernel_workspace/gcc-32/bin/arm-linux-androideabi-" >> $GITHUB_ENV
          fi

      - name: Download Custom-Gcc
        if: env.USE_CUSTOM_GCC_64 == 'true' || env.USE_CUSTOM_GCC_32 == 'true'
        run: |
          cd $GITHUB_WORKSPACE/kernel_workspace
          if [ ${{ env.USE_CUSTOM_GCC_64 }} = true ]; then
            if [[ ${{ env.CUSTOM_GCC_64_SOURCE }} =~ git ]]; then
                if [[ ${{ env.CUSTOM_GCC_64_SOURCE }} == *'.tar.gz' ]]; then
                  wget -O gcc-64.tar.gz ${{ env.CUSTOM_GCC_64_SOURCE }}
                  mkdir gcc-64
                  tar -C gcc-64/ -zxvf gcc-64.tar.gz
                else
                  git clone ${{ env.CUSTOM_GCC_64_SOURCE }} -b ${{ env.CUSTOM_GCC_64_BRANCH }} gcc-64 --depth=1
                fi
            else
                wget -O gcc-64.zip ${{ env.CUSTOM_GCC_64_SOURCE }}
                mkdir gcc-64
                unzip gcc-64.zip -d gcc-64/
            fi
            echo "GCC_64=CROSS_COMPILE=$GITHUB_WORKSPACE/kernel_workspace/gcc-64/bin/${{ env.CUSTOM_GCC_64_BIN }}" >> $GITHUB_ENV
          fi
          
          if [ ${{ env.USE_CUSTOM_GCC_32 }} = true ]; then
            if [[ ${{ env.CUSTOM_GCC_32_SOURCE }} =~ git ]]; then
                if [[ ${{ env.CUSTOM_GCC_32_SOURCE }} == *'.tar.gz' ]]; then
                  wget -O gcc-32.tar.gz ${{ env.CUSTOM_GCC_32_SOURCE }}
                  mkdir gcc-32
                  tar -C gcc-32/ -zxvf gcc-32.tar.gz
                else
                  git clone ${{ env.CUSTOM_GCC_32_SOURCE }} -b ${{ env.CUSTOM_GCC_32_BRANCH }} gcc-32 --depth=1
                fi
            else
              wget -O gcc-32.zip ${{ env.CUSTOM_GCC_32_SOURCE }}
              mkdir gcc-32
              unzip gcc-32.zip -d gcc-32/
            fi
            echo "GCC_32=CROSS_COMPILE_ARM32=$GITHUB_WORKSPACE/kernel_workspace/gcc-32/bin/${{ env.CUSTOM_GCC_32_BIN }}" >> $GITHUB_ENV
          fi

      - name: Download mkbootimg tools
        if: env.BUILD_BOOT_IMG == 'true'
        run: |
          cd $GITHUB_WORKSPACE/kernel_workspace
          git clone https://android.googlesource.com/platform/system/tools/mkbootimg tools -b master-kernel-build-2022 --depth=1

      - name: Download kernel source
        run: |
          cd $GITHUB_WORKSPACE/kernel_workspace
          wget -O kernel.zip "${{ env.KERNEL_SOURCE }}/archive/refs/heads/${{ env.KERNEL_SOURCE_BRANCH }}.zip"
          unzip kernel.zip
          SRC_DIR=$(find . -maxdepth 1 -type d ! -name "." | grep -v "kernel_workspace" | head -n 1)
          mkdir android-kernel
          mv "$SRC_DIR"/* android-kernel/
          rm -rf "$SRC_DIR"

      - name: Download source boot image
        if: env.BUILD_BOOT_IMG == 'true'
        run: |
          cd $GITHUB_WORKSPACE/kernel_workspace
          wget -O boot-source.img ${{ env.SOURCE_BOOT_IMAGE }}
          if [ -f boot-source.img ]; then
              echo "FORMAT_MKBOOTING=$(echo `tools/unpack_bootimg.py --boot_img=boot-source.img --format mkbootimg`)" >> $GITHUB_ENV
              echo "HAVE_SOURCE_BOOT_IMAGE=true" >> $GITHUB_ENV
          fi

      - name: Setup ReSukiSU
        if: env.ENABLE_RESUKISU == 'true'
        run: |
          cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel
          curl -LSs "https://raw.githubusercontent.com/ReSukiSU/ReSukiSU/main/kernel/setup.sh" | bash -s ${{ env.RESUKISU_TAG }}
          cd ./KernelSU
          KSU_VERSION=$(expr $(/usr/bin/git rev-list --count HEAD) "+" 10200)
          echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
          export KSU_VERSION=$KSU_VERSION
          sed -i "s/DKSU_VERSION=12800/DKSU_VERSION=${KSU_VERSION}/" kernel/Makefile

      - name: Add Configuration for ReSukiSU
        run: |
          cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel
          CONFIG_FILE=arch/${{ env.ARCH }}/configs/${{ env.KERNEL_CONFIG }}
          
          # Neccssary
          echo "CONFIG_KSU=y" >> "$CONFIG_FILE"
          echo "# CONFIG_KPROBES is not set" >> "$CONFIG_FILE"
          echo "CONFIG_HAVE_SYSCALL_TRACEPOINTS=y" >> "$CONFIG_FILE"
          
          if [ ${{ env.ENABLE_KPM }} = true ]; then
            echo "CONFIG_KPM=y" >> "$CONFIG_FILE"
            sed -i 's/# CONFIG_KALLSYMS_ALL is not set/CONFIG_KALLSYMS_ALL=y/g' arch/${{ env.ARCH }}/configs/${{ env.KERNEL_CONFIG }}
          fi
          
          if [ ${{ env.SUSFS_ENABLE }} == true ]; then
            echo "CONFIG_KSU_MANUAL_HOOK=n" >> "$CONFIG_FILE"
            echo "CONFIG_KSU_NONE_HOOK=y" >> "$CONFIG_FILE"
          
          else
            echo "CONFIG_KSU_MANUAL_HOOK=y" >> "$CONFIG_FILE"
          fi
          
          if [ ${{ env.SUSFS_ENABLE }} == true ]; then
            # SUSFS config
            echo "CONFIG_KSU_SUSFS=y" >> "$CONFIG_FILE"
            echo "CONFIG_KSU_SUSFS_SUS_PATH=y" >> "$CONFIG_FILE"
            echo "CONFIG_KSU_SUSFS_SUS_MOUNT=y" >> "$CONFIG_FILE"
            echo "CONFIG_KSU_SUSFS_SUS_KSTAT=y" >> "$CONFIG_FILE"
            echo "CONFIG_KSU_SUSFS_SPOOF_UNAME=y" >> "$CONFIG_FILE"
            echo "CONFIG_KSU_SUSFS_ENABLE_LOG=y" >> "$CONFIG_FILE"
            echo "CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=n" >> "$CONFIG_FILE"
            echo "CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG=y" >> "$CONFIG_FILE"
            echo "CONFIG_KSU_SUSFS_OPEN_REDIRECT=y" >> "$CONFIG_FILE"
            echo "CONFIG_KSU_SUSFS_SUS_MAP=n" >> "$CONFIG_FILE"
          
            if grep -q "THREAD_INFO_IN_TASK" "drivers/kernelsu/Kconfig"; then
              echo "CONFIG_THREAD_INFO_IN_TASK=y" >> "$CONFIG_FILE"
            fi
          fi
          
          if [ ${{ env.DISABLE-LTO }} = true ]; then
            sed -i 's/CONFIG_LTO=y/CONFIG_LTO=n/' arch/${{ env.ARCH }}/configs/${{ env.KERNEL_CONFIG }}
            sed -i 's/CONFIG_LTO_CLANG=y/CONFIG_LTO_CLANG=n/' arch/${{ env.ARCH }}/configs/${{ env.KERNEL_CONFIG }}
            sed -i 's/CONFIG_THINLTO=y/CONFIG_THINLTO=n/' arch/${{ env.ARCH }}/configs/${{ env.KERNEL_CONFIG }}
            echo "CONFIG_LTO_NONE=y" >> arch/${{ env.ARCH }}/configs/${{ env.KERNEL_CONFIG }}
          fi
          if [ ${{ env.DISABLE_CC_WERROR }} = true ]; then
            echo "CONFIG_CC_WERROR=n" >> arch/${{ env.ARCH }}/configs/${{ env.KERNEL_CONFIG }}
          fi

      - name: Check defconfig before build
        run: |
          cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel
          CONFIG_FILE="arch/${{ env.ARCH }}/configs/${{ env.KERNEL_CONFIG }}"
          echo "=== Checking defconfig file: $CONFIG_FILE ==="
          cat "$CONFIG_FILE" | grep -E "(KPM|KALLSYMS|KSU|SUFS)" || true  

      - name: Patch SUSFS
        if: env.SUSFS_ENABLE == 'true'
        run: |
          cd $GITHUB_WORKSPACE/kernel_workspace
          git clone https://github.com/lululalei64/susfs4ksu.git -b kernel-4.19-dev-2
          
          cd android-kernel
          echo "正在给内核打susfs补丁"
          
          cp ../susfs4ksu/kernel_patches/susfs_patch_to_4.19.patch .
          
          patch -p1 -f < susfs_patch_to_4.19.patch
          echo "完成补丁"
          
          echo "开始patch susfs inline"
          bash $GITHUB_WORKSPACE/patches/susfs_inline_hook_patches.sh
          echo "[+] executed SuSFS inline hook successfully."
          
          echo "开始backport"
          bash $GITHUB_WORKSPACE/patches/backport_patches.sh
          echo "[+] executed backport patch successfully."
          
          echo "开始backport selinux"
          bash $GITHUB_WORKSPACE/patches/backport_selinux_patches.sh
          echo "[+] Patched SELinux."

      - name: Apply Hide Stuff Patches
        if: env.HIDE_STUFF == 'true'
        run: |
          cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel
          echo "正在打隐藏应用补丁"
          if grep -q "show_vma_header_prefix_fake" "fs/proc/task_mmu.c"; then
            echo "[+] Found show_vma_header_prefix_fake."
          else
            spatch --sp-file $GITHUB_WORKSPACE/HideStuff/added_show_vma_header_prefix_fake.cocci --in-place fs/proc/task_mmu.c
            echo "[+] Added show_vma_header_prefix_fake."
          fi
          
          if grep -q "struct dentry \*dentry" "fs/proc/task_mmu.c"; then
            echo "[+] Found variable."
          else
            sed -i '/const char \*name = NULL;/a\    struct dentry *dentry;' fs/proc/task_mmu.c
            echo "[+] Added dentry."
          fi
          
          if grep -q "jit-zygote-cache" "fs/proc/task_mmu.c"; then
            echo "[+] Found hide stuff."
          else
            spatch --sp-file $GITHUB_WORKSPACE/HideStuff/function_hide_stuff.cocci --in-place fs/proc/task_mmu.c
            echo "[+] Added hide stuff."
          fi
          
          if grep -q "bypass:" "fs/proc/task_mmu.c"; then
            echo "[+] Found bypass."
          else
            if grep -q 'if (show_vma_header_prefix' "fs/proc/task_mmu.c"; then
                perl -i -0pe 's/(if \(show_vma_header_prefix\(m, start, end, flags, pgoff, dev, ino\)\)\s+return;)/$1\nbypass:/s' fs/proc/task_mmu.c
                echo "[+] Added bypass."
            else
                sed -i '/show_vma_header_prefix(m, start, end, flags, pgoff, dev, ino);/a\bypass:' fs/proc/task_mmu.c
                echo "[+] Added bypass."
            fi
          fi
          
          if grep -q "lineage" "fs/proc/base.c"; then
            echo "[+] Found hide stuff part ii."
          else
            spatch --sp-file $GITHUB_WORKSPACE/HideStuff/function_hide_stuff_partii.cocci --in-place fs/proc/base.c
            echo "[+] Added hide stuff part ii."
          fi

          if grep -q "/dev/ashmem" "fs/proc/task_mmu.c"; then
            sed -i 's|"/dev/ashmem (deleted)"|"/system/framework/framework-res.apk"|' fs/proc/task_mmu.c
            sed -i 's|"/dev/ashmem (deleted)"|"/system/framework/framework-res.apk"|' fs/proc/base.c
            echo "[+] Changed ashmem to framework-res."
          fi
      

      - name: Extra patch
        run: |
          cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel
          sed -i 's/MODULE_IMPORT_NS(VFS_internal_I_am_really_a_filesystem_and_am_NOT_a_driver);/#if LINUX_VERSION_CODE >= KERNEL_VERSION(5, 4, 0)\nMODULE_IMPORT_NS(VFS_internal_I_am_really_a_filesystem_and_am_NOT_a_driver);\n#endif/' drivers/kernelsu/ksu.c
          grep -rl "TWA_RESUME" drivers/kernelsu/ | xargs sed -i 's/TWA_RESUME/true/g'
          sed -i 's/#include <linux\/pgtable.h>/#if LINUX_VERSION_CODE >= KERNEL_VERSION(5, 8, 0)\n#include <linux\/pgtable.h>\n#else\n#include <asm\/pgtable.h>\n#endif/g' drivers/kernelsu/sucompat.c
          echo "End extra patching"

      - name: Setup ccache
        if: env.ENABLE_CCACHE == 'true'
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: build-kernel-${{ env.DEVICE }}${{ env.LOCALVERSION }}${{ env.UPLOADNAME }}
          max-size: 2G

      - name: Build kernel
        run: |
          cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel
          rm -f localversion-st
          export LOCALVERSION=""
          export CONFIG_LOCALVERSION_AUTO=n
          export KBUILD_BUILD_USER=android
          export KBUILD_BUILD_HOST=aosp
          export PATH=$GITHUB_WORKSPACE/kernel_workspace/clang-aosp/bin:$PATH
          make -j4 CC=clang O=out ARCH=${{ env.ARCH }} ${{ env.CUSTOM_CMDS }} ${{ env.EXTRA_CMDS }} ${{ env.GCC_64 }} ${{ env.GCC_32 }} ${{ env.KERNEL_CONFIG }}
          if [ ${{ env.ENABLE_CCACHE }} = true ]; then
              make -j$(nproc --all) CC="ccache clang" O=out ARCH=${{ env.ARCH }} ${{ env.CUSTOM_CMDS }} ${{ env.EXTRA_CMDS }} ${{ env.GCC_64 }} ${{ env.GCC_32 }} \
              KCFLAGS="-w -Wno-error -Wno-error=format -Wno-error=gnu-variable-sized-type-not-at-end -Wno-error=pointer-to-int-cast -Wno-error=address-of-packed-member -Wno-error=stringop-truncation -Wno-error=misleading-indentation -Wno-error=array-bounds"
          
          else
              make -j4 CC=clang O=out ARCH=${{ env.ARCH }} ${{ env.CUSTOM_CMDS }} ${{ env.EXTRA_CMDS }} ${{ env.GCC_64 }} ${{ env.GCC_32 }} \
              KCFLAGS="-w -Wno-error -Wno-error=format -Wno-error=gnu-variable-sized-type-not-at-end -Wno-error=pointer-to-int-cast -Wno-error=address-of-packed-member -Wno-error=stringop-truncation -Wno-error=misleading-indentation -Wno-error=array-bounds"
          
          fi

      - name: Show kernel build output
        run: |
          echo "=== Kernel build output files ==="
          cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel/out
          echo "Current path: $(pwd)"
          echo "--- arch/${{ env.ARCH }}/boot ---"
          ls -al arch/${{ env.ARCH }}/boot || echo "boot folder not found"
          echo "--- modules (.ko) ---"
          find . -name "*.ko" | sed 's/^/  /' || true

      - name: Check a kernel output files
        run: |
          cd $GITHUB_WORKSPACE/kernel_workspace
          if [ -f android-kernel/out/arch/${{ env.ARCH }}/boot/${{ env.KERNEL_IMAGE_NAME }} ]; then
              echo "CHECK_FILE_IS_OK=true" >> $GITHUB_ENV
          else
              echo "Kernel output file is empty"
              exit 1
          fi
          if [ ${{ env.NEED_DTBO }} = true ]; then
              if [ -f android-kernel/out/arch/${{ env.ARCH }}/boot/dtbo.img ]; then
                  echo "CHECK_DTBO_IS_OK=true" >> $GITHUB_ENV
              else
                  echo "DTBO image is empty"
                  exit 1
              fi
          fi

      - name: Make Anykernel3
        if: env.CHECK_FILE_IS_OK == 'true' && env.USE_CUSTOM_ANYKERNEL3 != 'true'
        run: |
          cd $GITHUB_WORKSPACE/kernel_workspace
          git clone https://github.com/osm0sis/AnyKernel3 --depth=1 AnyKernel3
          sed -i 's/do.devicecheck=1/do.devicecheck=0/g' AnyKernel3/anykernel.sh
          sed -i 's!BLOCK=/dev/block/platform/omap/omap_hsmmc.0/by-name/boot;!BLOCK=auto;!g' AnyKernel3/anykernel.sh
          sed -i 's/IS_SLOT_DEVICE=0;/is_slot_device=auto;/g' AnyKernel3/anykernel.sh
          cp android-kernel/out/arch/${{ env.ARCH }}/boot/${{ env.KERNEL_IMAGE_NAME }} AnyKernel3/
          if [ ${{ env.CHECK_DTBO_IS_OK }} = true ]; then
              cp android-kernel/out/arch/${{ env.ARCH }}/boot/dtbo.img AnyKernel3/
          fi
          rm -rf AnyKernel3/.git* AnyKernel3/README.md

      - name: Make Custom-Anykernel3
        if: env.CHECK_FILE_IS_OK == 'true' && env.USE_CUSTOM_ANYKERNEL3 == 'true'
        run: |
          cd $GITHUB_WORKSPACE/kernel_workspace
          if [[ ${{ env.CUSTOM_ANYKERNEL3_SOURCE }} =~ git ]]; then
              if [[ ${{ env.CUSTOM_ANYKERNEL3_SOURCE }} == *'.tar.gz' ]]; then
                  wget -O AnyKernel3.tar.gz ${{ env.CUSTOM_ANYKERNEL3_SOURCE }}
                  mkdir AnyKernel3
                  tar -C AnyKernel3/ -zxvf AnyKernel3.tar.gz
              else
                  git clone ${{ env.CUSTOM_ANYKERNEL3_SOURCE }} -b ${{ env.CUSTOM_ANYKERNEL3_BRANCH }} --depth=1 AnyKernel3
              fi
          else
              wget -O AnyKernel3.zip ${{ env.CUSTOM_ANYKERNEL3_SOURCE }}
              mkdir AnyKernel3
              unzip AnyKernel3.zip -d AnyKernel3/
          fi
          cp android-kernel/out/arch/${{ env.ARCH }}/boot/${{ env.KERNEL_IMAGE_NAME }} AnyKernel3/
          if [ ${{ env.CHECK_DTBO_IS_OK }} = true ]; then
              cp android-kernel/out/arch/${{ env.ARCH }}/boot/dtbo.img AnyKernel3/
          fi
          rm -rf AnyKernel3/.git* AnyKernel3/README.md

      - name: Make boot image
        if: env.HAVE_SOURCE_BOOT_IMAGE == 'true' && env.CHECK_FILE_IS_OK == 'true'
        run: |
          cd $GITHUB_WORKSPACE/kernel_workspace
          tools/unpack_bootimg.py --boot_img boot-source.img
          cp android-kernel/out/arch/${{ env.ARCH }}/boot/${{ env.KERNEL_IMAGE_NAME }} out/kernel
          tools/mkbootimg.py ${{ env.FORMAT_MKBOOTING }} -o boot.img
          if [ -f boot.img ]; then
              echo "MAKE_BOOT_IMAGE_IS_OK=true" >> $GITHUB_ENV
          else
              echo "Boot image is empty"
              exit 1
          fi

      - name: Upload ${{ env.KERNEL_IMAGE_NAME }}
        if: env.CHECK_FILE_IS_OK == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.KERNEL_IMAGE_NAME }}${{ env.LOCALVERSION }}${{ env.UPLOADNAME }}-${{ env.DEVICE }}-${{ env.BUILD_TIME }}
          path: kernel_workspace/android-kernel/out/arch/${{ env.ARCH }}/boot/${{ env.KERNEL_IMAGE_NAME }}

      - name: Upload AnyKernel3
        if: env.CHECK_FILE_IS_OK == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: AnyKernel3${{ env.LOCALVERSION }}${{ env.UPLOADNAME }}-${{ env.DEVICE }}-${{ env.BUILD_TIME }}
          path: kernel_workspace/AnyKernel3/*

      - name: Upload DTBO image
        if: env.CHECK_DTBO_IS_OK == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: dtbo-${{ env.DEVICE }}-${{ env.BUILD_TIME }}
          path: kernel_workspace/android-kernel/out/arch/${{ env.ARCH }}/boot/dtbo.img

      - name: Upload boot image
        if: env.MAKE_BOOT_IMAGE_IS_OK == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: boot${{ env.LOCALVERSION }}${{ env.UPLOADNAME }}-${{ env.DEVICE }}-${{ env.BUILD_TIME }}
          path: kernel_workspace/boot.img
